services:
  node-application:
    build: .
    container_name: node-application
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      DATABASE_URL: sqlite:///books-catalogue
    depends_on:
      - db

  db:
    image: node:alpine
    container_name: db
    volumes:
      - ./books-catalogue:/db
    command: ["sh", "-c", "apk add --no-cache sqlite"]